# Generated by Django 3.2.8 on 2021-12-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('valuta', models.CharField(blank=True, max_length=200, null=True)),
                ('descrizione', models.CharField(blank=True, max_length=200, null=True)),
                ('addebiti', models.CharField(blank=True, max_length=200, null=True)),
                ('accrediti', models.CharField(blank=True, max_length=200, null=True)),
                ('descrizioneestesa', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
